# Generated by Django 4.1.1 on 2022-10-17 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor_name', models.CharField(max_length=120, null=True)),
                ('instructor_email', models.CharField(max_length=60, null=True)),
                ('course_num', models.CharField(max_length=20, null=True)),
                ('semester_code', models.CharField(max_length=20, null=True)),
                ('section', models.CharField(max_length=5, null=True)),
                ('subject', models.CharField(max_length=5, null=True)),
                ('course_cat', models.CharField(max_length=20, null=True)),
                ('course_name', models.CharField(max_length=150, null=True)),
                ('units', models.CharField(max_length=5, null=True)),
                ('component', models.CharField(max_length=5, null=True)),
                ('capacity', models.CharField(max_length=20, null=True)),
                ('wait_list', models.CharField(max_length=5, null=True)),
                ('wait_cap', models.CharField(max_length=5, null=True)),
                ('enrollment_total', models.CharField(max_length=5, null=True)),
                ('enrollment_available', models.CharField(max_length=5, null=True)),
                ('topic', models.CharField(max_length=100, null=True)),
                ('location', models.CharField(max_length=70, null=True)),
                ('meeting_days', models.CharField(max_length=20, null=True)),
                ('start_time', models.CharField(max_length=30, null=True)),
                ('end_time', models.CharField(max_length=30, null=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.department')),
            ],
        ),
    ]
