# Generated by Django 4.1.1 on 2022-11-07 22:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_slug', models.CharField(max_length=15, null=True)),
                ('instructor_name', models.CharField(max_length=120, null=True)),
                ('instructor_email', models.CharField(max_length=60, null=True)),
                ('course_num', models.CharField(max_length=20, null=True)),
                ('semester_code', models.CharField(max_length=20, null=True)),
                ('section', models.CharField(max_length=20, null=True)),
                ('subject', models.CharField(max_length=20, null=True)),
                ('course_cat', models.CharField(max_length=20, null=True)),
                ('course_name', models.CharField(max_length=1200, null=True)),
                ('units', models.CharField(max_length=20, null=True)),
                ('component', models.CharField(max_length=20, null=True)),
                ('capacity', models.CharField(max_length=20, null=True)),
                ('wait_list', models.CharField(max_length=20, null=True)),
                ('wait_cap', models.CharField(max_length=20, null=True)),
                ('enrollment_total', models.CharField(max_length=20, null=True)),
                ('enrollment_available', models.CharField(max_length=20, null=True)),
                ('topic', models.CharField(max_length=100, null=True)),
                ('location', models.CharField(max_length=70, null=True)),
                ('meeting_days', models.CharField(max_length=20, null=True)),
                ('start_time', models.CharField(max_length=30, null=True)),
                ('end_time', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friends', models.ManyToManyField(related_name='friends', to=settings.AUTH_USER_MODEL)),
                ('saved_courses', models.ManyToManyField(to='app.course')),
                ('scheduled_courses', models.ManyToManyField(related_name='user_schedule', to='app.course')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='department_ptr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.department'),
        ),
    ]
