# Generated by Django 4.1.1 on 2022-10-16 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='capacity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_num',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='semester_code',
            field=models.IntegerField(),
        ),
    ]
