# Generated by Django 4.1.1 on 2022-10-16 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='subject',
        ),
        migrations.AddField(
            model_name='department',
            name='slug',
            field=models.SlugField(max_length=10, null=True),
        ),
    ]
