# Generated by Django 4.1.1 on 2022-11-05 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='saved_courses',
            field=models.ManyToManyField(blank=True, null=True, to='app.course'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='scheduled_courses',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_schedule', to='app.course'),
        ),
    ]
