# Generated by Django 4.1.1 on 2022-11-05 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_userprofile_saved_courses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='saved_courses',
            field=models.ManyToManyField(to='app.course'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='scheduled_courses',
            field=models.ManyToManyField(related_name='user_schedule', to='app.course'),
        ),
    ]
