# Generated by Django 4.1.1 on 2022-10-18 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_course_component_alter_course_course_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='slug',
            new_name='subject',
        ),
    ]
