# Generated by Django 4.1.1 on 2022-10-18 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_slug_department_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='subject',
            new_name='slug',
        ),
    ]
